version: '3.8'

services:
  web:
    build: ./app
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./app/:/usr/src/app/
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
    depends_on:
      - db
  db:
    
    
    image: postgis/postgis:15-3.4
    restart: always
    # expose:
    #   - "5432"
    # ports:
    #   - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
    - ./.env.dev.db
       
       

       


volumes:
  postgres_data:
