# Generated by Django 4.2.3 on 2024-01-28 00:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0002_remove_shop_city'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Shop',
            new_name='Hotel',
        ),
    ]
